name: Build Artifacts

on:
  push:
    branches:
      - main


jobs:

  create-release:
    name: Create Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To ensure we have all tags        

      - name: Get the Newest Tag
        id: newest-tag
        run: |
          echo "version=`git tag --list "v[0-9]*.[0-9]*.[0-9]*" --sort=-v:refname | head -n1 | cut -c2-`" >> "$GITHUB_OUTPUT"    

      - name: Checkout test-receivert
        uses: actions/checkout@v3
        with:
          repository: "jagedn/test-receiver"
          path: test-receiver-tmp

      - name: Open Pull Request
        working-directory: test-receiver-tmp
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          git pull
          git checkout -b "release-v"
          echo $(date) >> test-receiver-tmp/list.json
          git commit -a -m "add your message"
          gh pr create --fill --repo "jagedn/test-receiver"          
