name: Build Artifacts

on:
  push:
    branches:
      - main


jobs:

  create-release:
    name: Create Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # To ensure we have all tags        

      - name: Checkout test-receiver
        uses: actions/checkout@v3
        with:
          repository: "jagedn/test-receiver"
          path: test-receiver-tmp

      - name: Open Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          CLONE_DIR=$(mktemp -d)
          cd "$CLONE_DIR"
          git clone --single-branch --branch main "https://x-access-token:$RELEASE_TOKEN@github.com/jagedn/test-receiver.git" "$CLONE_DIR"
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          git checkout -b "release-v"
          
          echo $(date) >> list.json

          git commit -a --message "probando probando new release"
          git push -u origin HEAD:release-v
          
          gh pr create --fill --repo "jagedn/test-receiver"          
